language: en

favicon: /favicon.ico


author:
  name: 银河渡舟
  avatar: /assets/avatar.png
  signature: 永远相信美好的事情即将发生
  social:
    - name: qq
      link: #
      icon: iconfont icon-qq
      color: "#1a98ff"
    - name: bilibili
      link: #
      icon: iconfont icon-bilibili
      color: "#fc87b2"
    - name: netease music
      link: #
      icon: iconfont icon-netease-music
      color: "#ff4e6a"
    - name: github
      link: #
      icon: iconfont icon-github
      color: "#003665"
    - name: telegram
      link: #
      icon: iconfont icon-telegram
      color: "#00dbff"
    - name: mail
      link: #
      icon: iconfont icon-mail
      color: "#15ce05"
    - name: zhihu
      link: #
      icon: iconfont icon-zhihu
      color: "#1e88e5"
    - name: weibo
      link: #
      icon: iconfont icon-weibo
      color: "#ff3b00"

header: 
  cover: /sample.jpg


navigator:
  logo:
    image: /favicon.ico
    text: 银河渡舟
  menu:
    - name: 博客
      url: /
    - name: 菜单
      submenu: 
        - name: 标签
          url: /tags
        - name: 归档
          url: /archives
        - divider
        - name: 友链
          url: /friends
        - name: 关于
          submenu:
            - name: 标签
              url: /tags
            - name: 归档
              url: /archives
            - name: 友链
              url: /friends
            - name: 关于
              submenu:
                - name: 标签
                  url: /tags
                - name: 归档
                  url: /archives
                - name: 友链
                  url: /friends
                - name: 关于
                  submenu:
                    - name: 标签
                      url: /tags
                    - name: 归档
                      url: /archives
                    - name: 友链
                      url: /friends
                    - name: 关于
                      submenu:
                        - name: 标签
                          url: /tags
                        - name: 归档
                          url: /archives
                        - name: 友链
                          url: /friends
                        - name: 关于
                          submenu:
                            - name: 标签
                              url: /tags
                            - name: 归档
                              url: /archives
                            - name: 友链
                              url: /friends
                            - name: 关于
                              url: /about
    - name: 分类
      url: /categories
    - name: 标签
      url: /tags
    - name: 归档
      url: /archives
    - name: 友链
      url: /friends
    - name: 关于
      url: /about
  search: #

sidebar:
  show_profile: true
  show_tag_cloud: true
  show_category_tree: true
  show_toc: true

footer: #

comments:
  disqus:
    enable: false
    shortname: wider-blog
  disqusjs:
    enable: true
    shortname: wider-blog
    # 你的 Disqus shortname
    sitename: wider-blog
    # 你站点的名称，将会显示在「评论基础模式」的 header 中；该配置应该和 Disqus Admin - Settings - General - Website Name 一致
    api: https://disqus.wider.ink/ # DisqusJS 请求的 API Endpoint，通常情况下你应该配置一个 Disqus API 的反代并填入反代的地址。你也可以直接使用 DISQUS 官方 API 的 Endpoint https://disqus.com/api/，或是使用SukkaW搭建的 Disqus API 反代 Endpoint https://disqus.skk.moe/disqus/。
    apikey: M5F28pZTEcNupBr2Ku4L5AKqZ1mtHYePVq7hYRL6UKh8oaxvXHou5HxwlbOSkaxL
    # DisqusJS 向 API 发起请求时使用的 API Key，你应该在配置 Disqus Application 时获取了 API Key;DisqusJS 支持填入一个 包含多个 API Key 的 Array，在每次请求时会随机使用其中一个；如果你只需要填入一个 API Key，则可以填入 String 或 Array。
    #admin: GREDIW
    # 你的站点的 Disqus Moderator 的用户名（也就是你的用户名）。你可以在 Disqus - Settings - Account - Username 获取你的 Username
    #adminLabel: 银河渡舟
    # 你想显示在 Disqus Moderator Badge 中的文字。该配置应和 Disqus Admin - Settings - Community - Moderator Badge Text 相同


plugins:
  katex: true
  anchor: false
